Resources:
  RequestLetterSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      ContentBasedDeduplication: false
      FifoTopic: true
      KmsMasterKeyId:
        Ref: CustomMasterKey
      TopicName: ${self:custom.variables.request-sns-topic-name}
