service: eip-messaging-aggregator

custom:
  variables: ${file(serverless/variables.yml)}
  prune:
    automatic: true
    number: 1

frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  environment: ${file(serverless/env.yml):${self:provider.stage}}
  apiGateway:
    minimumCompressionSize: 1024
  deploymentBucket:
    name: ${self:provider.environment.SERVERLESS_DEPLOYMENT_BUCKET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
        - SNS:Subscribe
      Resource:
        - ${self:custom.variables.request-sns-topic-arn}
        - ${self:custom.variables.reply-a-sns-topic-arn}
        - ${self:custom.variables.reply-b-sns-topic-arn}
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: "*"

functions:
  # Requester
  - ${file(serverless/requester/functions/aggregator.yml)}
  - ${file(serverless/requester/functions/reply.yml)}
  - ${file(serverless/requester/functions/requester.yml)}

  # Replier A
  - ${file(serverless/replier-a/functions/replier-a.yml)}

  # Replier B
  - ${file(serverless/replier-b/functions/replier-b.yml)}

resources:
  # Communication bridge
  - ${file(serverless/communication-bridge/resources/aws-kms-key.yml)}
  - ${file(serverless/communication-bridge/resources/aws-sns-requester-topic.yml)}
  - ${file(serverless/communication-bridge/resources/aws-sns-replier-a-topic.yml)}
  - ${file(serverless/communication-bridge/resources/aws-sns-replier-b-topic.yml)}

  # Requester
  - ${file(serverless/requester/resources/aws-kinesis-letters-stream.yml)}
  - ${file(serverless/requester/resources/aws-sns-reply-a-letter-subscription.yml)}
  - ${file(serverless/requester/resources/aws-sns-reply-b-letter-subscription.yml)}
  - ${file(serverless/requester/resources/aws-sqs-reply-a-letter-queue.yml)}
  - ${file(serverless/requester/resources/aws-sqs-reply-b-letter-queue.yml)}

  # Replier A
  - ${file(serverless/replier-a/resources/aws-sns-request-a-letter-subscription.yml)}
  - ${file(serverless/replier-a/resources/aws-sqs-request-a-letter-queue.yml)}

  # Replier B
  - ${file(serverless/replier-b/resources/aws-sns-request-b-letter-subscription.yml)}
  - ${file(serverless/replier-b/resources/aws-sqs-request-b-letter-queue.yml)}
