Resources:
  LettersKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: ${self:custom.variables.letters-kinesis-stream-name}
      ShardCount: 2
      StreamEncryption:
        EncryptionType: KMS
        KeyId:
          Ref: CustomMasterKey

